apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: rgalicia0729/multi-server
          ports:
            - containerPort: 3001
          env:
            - name: PGHOST
              value: postgres-ip-service
            - name: PGPORT
              value: '5432'
            - name: PGUSER
              value: postgres
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD
            - name: PGDATABASE
              value: complex
            - name: REDIS_HOST
              value: redis-ip-service
            - name: REDIS_PORT
              value: '6379'
---
apiVersion: v1
kind: Service
metadata:
  name: server-ip-service
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - port: 3001
      targetPort: 3001
